from enum import Enum


class Error(Enum):
    HASH_ERROR_OK = 0
    HASH_ERROR_GENERAL = 1
    HASH_ERROR_EXCEPTION = 2
    HASH_ERROR_MEMORY = 3
    HASH_ERROR_LOG_EMPTY = 4
    HASH_ERROR_ARGUMENT_INVALID = 5
    HASH_ERROR_ARGUMENT_NULL = 6
    HASH_ERROR_NOT_INITIALIZED = 7
    HASH_ERROR_ALREADY_INITIALIZED = 8
